export const DEFAULT_ZONE = 'midfield';

export const ZONES = [
  { id: 'defense', label: 'Defense' },
  { id: 'midfield', label: 'Midfield' },
  { id: 'final_third', label: 'Final Third' },
  { id: 'box', label: 'Box' },
];

export const SEEDED_PLAYERS = [
  { id: 'player_1', name: 'Sezer Mintaz', position: 'GK', order: 1 },
  { id: 'player_2', name: 'Simon A', position: 'CB', order: 2 },
  { id: 'player_3', name: 'Recep A', position: 'RB', order: 3 },
  { id: 'player_4', name: 'Aykut A', position: 'CB', order: 4 },
  { id: 'player_5', name: 'Ersan A', position: 'LB', order: 5 },
  { id: 'player_6', name: 'Kubilay A', position: 'CM', order: 6 },
  { id: 'player_7', name: 'Resul A', position: 'CM', order: 7 },
  { id: 'player_8', name: 'Taner A', position: 'CM', order: 8 },
  { id: 'player_9', name: 'Soner A', position: 'RW', order: 9 },
  { id: 'player_10', name: 'Isa A', position: 'ST', order: 10 },
  { id: 'player_11', name: 'Mehmet A', position: 'ST', order: 11 },
  { id: 'player_12', name: 'Volkan A', position: 'LW', order: 12 },
];

export const EVENT_KEY_BINDINGS = {
  s: 'pass_success',
  d: 'pass_fail',
  a: 'key_pass',
  g: 'long_pass_success',
  h: 'long_pass_fail',
  f: 'throw_in_won',
  '7': 'blue_card',
  '8': 'yellow_card',
  '9': 'red_card',
  t: 'corner_taken',
  y: 'cross',
  u: 'error_leads_shot',
  i: 'error_leads_goal',
  x: 'shot_on',
  c: 'shot_off',
  z: 'shot_blocked',
  v: 'goal',
  '0': 'big_chance_won',
  '5': 'create_big_chance',
  '-': 'penalty_won',
  ',': 'substitution',
  b: 'offside',
  '6': 'cross_fail',
  n: 'dribble_success',
  m: 'dribble_fail',
  q: 'tackle_win',
  w: 'interception',
  e: 'clearance',
  r: 'block',
  j: 'ball_loss',
  k: 'aerial_win',
  l: 'aerial_fail',
  o: 'foul_committed',
  p: 'foul_won',
};

export const EVENT_TYPE_LABELS = {
  pass_success: 'Pass Success',
  pass_fail: 'Pass Fail',
  key_pass: 'Key Pass',
  assist: 'Assist',
  blue_card: 'Blue Card',
  yellow_card: 'Yellow Card',
  red_card: 'Red Card',
  corner_taken: 'Corner',
  cross: 'Cross Success',
  cross_fail: 'Cross Fail',
  error_leads_shot: 'Error Leads to Shot',
  error_leads_goal: 'Error Leads to Goal',
  shot_on: 'Shot On Target',
  shot_off: 'Shot Off Target',
  shot_blocked: 'Shot Blocked',
  goal: 'Goal',
  create_big_chance: 'Create Big Chance',
  big_chance_won: 'Big Chance',
  big_chance_missed: 'Big Chance Missed',
  penalty_won: 'Penalty',
  substitution: 'Substitution',
  half_time_marker: 'Half Time',
  offside: 'Offside',
  shot_header: 'Shot Header',
  shot_inside_box: 'Shot Inside Box',
  shot_outside_box: 'Shot Outside Box',
  dribble_success: 'Dribble Success',
  dribble_fail: 'Dribble Fail',
  tackle_win: 'Tackle Win',
  interception: 'Interception',
  clearance: 'Clearance',
  block: 'Block',
  ball_loss: 'Ball Loss',
  aerial_win: 'Aerial Win',
  aerial_fail: 'Aerial Fail',
  foul_committed: 'Foul Committed',
  foul_won: 'Foul Won',
  throw_in_won: 'Throw ins',
  long_pass_success: 'Long Pass Success',
  long_pass_fail: 'Long Pass Fail',
  save: 'Save',
  goal_conceded: 'Goal Conceded',
};

const LEGACY_EVENT_TYPES = ['assist', 'shot_header', 'shot_inside_box', 'shot_outside_box', 'big_chance_missed'];

export const EVENT_TYPES = Object.keys(EVENT_TYPE_LABELS).filter((type) => !LEGACY_EVENT_TYPES.includes(type));

export const EVENT_TYPE_POINTS = {
  pass_success: 1,
  pass_fail: -1,
  key_pass: 2,
  assist: 3,
  blue_card: -1,
  yellow_card: -2,
  red_card: -4,
  corner_taken: 1,
  cross: 1,
  cross_fail: -1,
  error_leads_shot: -2,
  error_leads_goal: -4,
  shot_on: 2,
  shot_off: -1,
  shot_blocked: 0,
  goal: 5,
  create_big_chance: 2,
  big_chance_won: 2,
  big_chance_missed: -2,
  penalty_won: 0,
  substitution: 0,
  half_time_marker: 0,
  offside: -1,
  shot_header: 0,
  shot_inside_box: 0,
  shot_outside_box: 0,
  dribble_success: 2,
  dribble_fail: -1,
  tackle_win: 2,
  interception: 2,
  clearance: 1,
  block: 1,
  ball_loss: -2,
  aerial_win: 1,
  aerial_fail: -1,
  foul_committed: -1,
  foul_won: 1,
  throw_in_won: 0,
  long_pass_success: 1,
  long_pass_fail: -1,
  save: 3,
  goal_conceded: -3,
};

export const KEYBOARD_GROUPS = [
  { title: 'Pass', shortcuts: ['s pass_success', 'd pass_fail', 'a key_pass', 'g long_pass_success', 'h long_pass_fail', 'f throw_in_won'] },
  { title: 'Discipline', shortcuts: ['7 blue_card', '8 yellow_card', '9 red_card'] },
  { title: 'Set Piece', shortcuts: ['t corner_taken', 'y cross', '6 cross_fail', '- penalty_won', ', substitution'] },
  { title: 'Errors', shortcuts: ['u error_leads_shot', 'i error_leads_goal'] },
  {
    title: 'Shots',
    shortcuts: ['x shot_on', 'c shot_off', 'z shot_blocked', 'v goal', '0 big_chance_won', '5 create_big_chance', 'b offside'],
  },
  { title: 'Dribble', shortcuts: ['n dribble_success', 'm dribble_fail'] },
  { title: 'Defense', shortcuts: ['q tackle_win', 'w interception', 'e clearance', 'r block'] },
  { title: 'Other', shortcuts: ['j ball_loss', 'k aerial_win', 'l aerial_fail'] },
  { title: 'Foul', shortcuts: ['o foul_committed', 'p foul_won'] },
  { title: 'Control', shortcuts: ['Shift+Z undo', 'Ctrl+E edit selected', 'Space pause/resume'] },
];


